version: '3.1'

services:

  postgres:
    image: postgres
    container_name: postgres
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_HOST_AUTH_METHOD: trust
    volumes:
      - postgres-data:/var/lib/postgresql

  redis:
    image: redis:7.2.4-alpine
    restart: always
    command: redis-server --save 20 1 --loglevel warning --requirepass ''
    environment:
      - REDIS_PWD:""
      - REDIS_PORT=${REDIS_PORT}
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
    volumes:
      - redis-data:/data
    ports:
      - "${REDIS_PORT}:6379"

volumes:
  postgres-data:
  redis-data:
